name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}
          path: |
            ${GITHUB_WORKSPACE}/toolchain
            ${GITHUB_WORKSPACE}/buildroot/dl

      - name: Prepare
        run: ./scripts/prepare.sh

      - name: Build rootfs
        run: |
          git clone https://git.buildroot.net/buildroot ${GITHUB_WORKSPACE}/buildroot
          cp -v configs/buildroot_aarch64_defconfig ${GITHUB_WORKSPACE}/buildroot/configs/labbo_defconfig
          cd ${GITHUB_WORKSPACE}/buildroot
          git checkout origin/2022.08.x
          make ARCH=arm64 labbo_defconfig
          make ARCH=arm64 -j

      - name: Build Linux kernel
        run: |
          git clone https://github.com/torvalds/linux.git ${GITHUB_WORKSPACE}/linux
          cat configs/linux_kernel_defconfig >> ${GITHUB_WORKSPACE}/linux/arch/arm64/configs/defconfig
          cd ${GITHUB_WORKSPACE}/linux
          make ARCH=arm64 defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-none-linux-gnu- -j

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: |
            ${GITHUB_WORKSPACE}/toolchain

