name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}
          path: |
            ${GITHUB_WORKSPACE}/toolchain
            ${GITHUB_WORKSPACE}/buildroot/dl

      - name: Prepare
        run: ./scripts/prepare.sh

      - name: Build rootfs
        run: |
          sudo ./scripts/rootfs_ubuntu-base.sh ${GITHUB_WORKSPACE}

      - name: Build Linux kernel
        run: |
          echo "place holder"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: |
            /opt/fw

